export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const SET_CURRENT_CITY_FORECAST = "SET_CURRENT_CITY_FORECAST";
export const SET_CURRENT_CITY_WEATHER = "SET_CURRENT_CITY_WEATHER";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const RMV_FAVORITE = "RMV_FAVORITE";
export const CLEAR_FAVORITES = "CLEAR_FAVORITES";
export const SET_FAVORITES = "SET_FAVORITES";

export const TOGGLE_THEME = "TOGGLE_THEME";
export const TOGGLE_TEMP_UNIT = "TOGGLE_TEMP_UNIT";

export const SET_ERROR_MSG = "SET_ERROR_MSG";
export const CLEAR_ERROR_MSG = "CLEAR_ERROR_MSG";

export const SET_CURRENT_GEO = "SET_CURRENT_GEO";
